swagger: "2.0"
info:
  title: drbusers Simple API
  description: Very simple yaml file getting Users
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: er, it returns the users
      responses:
        '200':    # status code
          description: A JSON array of user names
          schema:
            $ref: "#/definitions/usersarray"
definitions:
  usersarray:
    type: array
    items:
      type: string
