// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Very simple yaml file getting Users",
    "title": "drbusers Simple API",
    "version": "1.0.0"
  },
  "paths": {
    "/users": {
      "get": {
        "description": "er, it returns the users",
        "summary": "Returns a list of users.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "$ref": "#/definitions/usersarray"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "usersarray": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}`))
}
